version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webappdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: secretpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      # Para SQLAlchemy con PyMySQL:
      DATABASE_URL: mysql+pymysql://webapp:secretpassword@db:3306/webappdb
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  db_data:

